var metaLoop=1E3,presetIndex=3,grid,x,y,dir,img,NORTH=0,EAST=1,SOUTH=2,WEST=3,scale=1,xPan,yPan,zoomIn=!1,zoomOut=!1,panUp=!1,panDown=!1,panLeft=!1,panRight=!1,panSpeed=10,zoomSpeed=1.1,directions=4,states=12,s0=1,s1=1,s2=0,s3=0,s4=0,s5=1,s6=0,s7=0,s8=0,s9=1,s10=1,s11=1;
function setup(){frameRate(2147483647);createCanvas(600,600);xPan=8*windowWidth;yPan=4.5*windowHeight;preset(presetIndex);img=createImage(width,height);img.loadPixels();img.updatePixels();image(img,0,0);grid=Array(width).fill().map(function(){return Array(height).fill(0)});x=width/2;y=height/2;dir=NORTH}
function preset(a){switch(a){case 0:states=2;s0=0;s1=1;break;case 1:states=3;s0=1;s1=0;s2=1;break;case 2:states=4;s1=s0=0;s3=s2=1;break;case 3:states=9;s0=0;s5=s4=s3=s2=s1=1;s7=s6=0;s8=1;break;case 4:states=12;s1=s0=0;s4=s3=s2=1;s5=0;s6=1;s7=0;s8=1;s10=s9=0;s11=1;break;case 5:states=12;s1=s0=1;s4=s3=s2=0;s5=1;s8=s7=s6=0;s11=s10=s9=1;break;case 6:states=4,s0=1,s2=s1=0,s3=1}}
function turn(){switch(grid[x][y]){case 0:dirChange(s0);break;case 1:dirChange(s1);break;case 2:dirChange(s2);break;case 3:dirChange(s3);break;case 4:dirChange(s4);break;case 5:dirChange(s5);break;case 6:dirChange(s6);break;case 7:dirChange(s7);break;case 8:dirChange(s8);break;case 9:dirChange(s9);break;case 10:dirChange(s10);break;case 11:dirChange(s11)}dir>=directions?dir=0:0>dir&&(dir=directions-1)}function dirChange(a){0===a?dir--:1===a&&dir++}
function changeState(){grid[x][y]++;grid[x][y]>=states&&(grid[x][y]=0)}
function changePixel(){switch(grid[x][y]){case 0:img.set(x,y,color(0,0,255));break;case 1:img.set(x,y,color(0,255,0));break;case 2:img.set(x,y,color(255,0,0));break;case 3:img.set(x,y,color(255,255,0));break;case 4:img.set(x,y,color(0,255,255));break;case 5:img.set(x,y,color(255,0,255));break;case 6:img.set(x,y,color(127,255,255));break;case 7:img.set(x,y,color(0,0,0));break;case 8:img.set(x,y,color(127,127,127));break;case 9:img.set(x,y,color(127,255,0));break;case 10:img.set(x,y,color(127,0,255));
break;case 11:img.set(x,y,color(255,255,255))}}function move(){switch(dir){case NORTH:y--;break;case EAST:x++;break;case SOUTH:y++;break;case WEST:x--}x>width-1?x=0:0>x&&(x=width-1);y>height-1?y=0:0>y&&(y=height-1)}function visionControl(){translate(width/2,height/2);scale(scale);translate(-xPan,-yPan);zoomIn&&(scale*=zoomSpeed);zoomOut&&(scale/=zoomSpeed);panUp&&(yPan-=panSpeed);panDown&&(yPan+=panSpeed);panLeft&&(xPan-=panSpeed);panRight&&(xPan+=panSpeed)}
function feedBack(){console.log("\r\n\r\n\r\nStep#:          "+frameCount+" M");console.log("Steps/s:        "+frameRate()+" M")}function draw(){for(var a=0;a<metaLoop;a++)turn(),changeState(),changePixel(),move();img.set(x,y,color(255,0,0));img.updatePixels();image(img,0,0);0==frameCount%100&&feedBack()}function mouseClicked(){console.log("Saving frame!");saveFrame()}
function keyPressed(){keyCode===UP_ARROW&&(zoomIn=!0,zoomOut=!1);keyCode===DOWN_ARROW&&(zoomOut=!0,zoomIn=!1);if("w"===key||"W"===key)panUp=!0,panDown=!1;if("s"===key||"S"===key)panDown=!0,panUp=!1;if("a"===key||"A"===key)panLeft=!0,panRight=!1;if("d"===key||"D"===key)panRight=!0,panLeft=!1}
function keyReleased(){keyCode===UP_ARROW&&(zoomIn=!1);keyCode===DOWN_ARROW&&(zoomOut=!1);if("w"===key||"W"===key)panUp=!1;if("s"===key||"S"===key)panDown=!1;if("a"===key||"A"===key)panLeft=!1;if("d"===key||"D"===key)panRight=!1};